# Write the pre-commit config for CI and local development environment
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0  # Use the latest version
    hooks:
    -   id: check-byte-order-marker
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: trailing-whitespace

  - repo: https://github.com/koalaman/shellcheck
    rev: v0.7.2
    hooks:
      - id: shellcheck

  - repo: https://github.com/pre-commit/mirrors-yamllint
    rev: v1.26.3
    hooks:
      - id: yamllint

  - repo: https://github.com/rust-lang/rustfmt
    rev: 1.5.0
    hooks:
      - id: rustfmt
        args: [--check]

  - repo: https://github.com/hadolint/hadolint
    rev: v2.1.0
    hooks:
      - id: hadolint
